### ISSUE TITLE
[Request/Bug] Click to enter Desktop is broken?

### ISSUE THREAD

**Issue by imPRAGMA** [rocksdanister/GBWallpaper#3]
[Bug](https://i.imgur.com/w5W2h8c.gif)
As you can see, with it enabled you cant click your desktop to go back to it. Not sure if its a bug or what.

**Comment by rocksdanister** [comment]
with what enabled? i don't understand the video.

**Comment by imPRAGMA** [comment]
Like would it be possible so if you click the desktop, it essentially minimizes all other windows?

**Comment by rocksdanister** [comment]
sounds intrusive yikes. Is it possible? probably, probably not a good idea though.

**Comment by imPRAGMA** [comment]
i guess :/
