### ISSUE TITLE
[Request] LibRetro support

### ISSUE THREAD

**Issue by Formedras** [rocksdanister/GBWallpaper#4]
I get that this isn't a simple change, but I think it's well worth it due to the massive increase in capability.
Basically, instead of using a built-in DMG emulation core, use LibRetro cores. If this works, that's immediate support for the NES, SNES, GBC, GBA, Genesis/Mega Drive, Master System, and numerous other systems.

**Comment by rocksdanister** [comment]
will look into it, I have something even better planned.

**Comment by rocksdanister** [comment]
discussion moved to: https://github.com/rocksdanister/lively
