### ISSUE TITLE
No Uninstall Option

### ISSUE THREAD

**Issue by crbenne** [rocksdanister/GBWallpaper#5]
I see that some registry keys are created and it sets itself to run on startup, how do I uninstall the program?

**Comment by rocksdanister** [comment]
I intend it as a portable application, so long as startup is not enabled.
open the application, run on startup -> disable it ..it will delete the registry key, then just delete the program folder.

or if you want u can just delete the key manually at:[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\Unity-GBWallpaper]
